{{- if .Values.enableGCLB }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
    name: {{ .Values.backendconfig.name }}
    namespace: istio-system
spec:
    timeoutSec: 90
    healthCheck:
        requestPath: /healthz/ready
        port: 15021
        type: HTTP
    {{- with .Values.WAF }}
    securityPolicy:
      name: {{ .name }}
    {{- end }}
{{- end }}