apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.coreGateway.name }}
  namespace: {{ .Values.coreNamespace }}
spec:
  {{- with .Values.gateway.labels }}
  selector:
  {{ toYaml .| indent 2 }}
  {{- end }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
